### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Dexxa1024** [MagnaCapax/PMSS#77]
I've tried a number of times  but cant seem to get it to install, all i keep getting is

dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Setting up git-man (1:2.20.1-2+deb10u9) ...
Setting up git (1:2.20.1-2+deb10u9) ...
Processing triggers for man-db (2.8.5-2+deb10u1) ...
Errors were encountered while processing:
 grub-pc
E: Sub-process /usr/bin/dpkg returned an error code (1)
### Setting up software
install.sh: line 118: syntax error near unexpected token `$1'
install.sh: line 118: `parse_version_string($1)'

Im using debian 10, anyone know what im doing wrong?

Thanks

**Comment by ilzu** [comment]
Should be fixed now. My fingers were faster than my brain when doing last change and called function like it would be on other languages, but not on bash.
